### ISSUE TITLE
Update the Calendar app for the SDK version 0.100 f7

### ISSUE THREAD

**Issue by furippa** [techartdev/Calendar#1]
Hello!

Your Calendar app version `1.0` fails to build with the SDK version `0.100.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/65d25c86f6103d1702fefdcc/page)

Flipper Team

**Comment by furippa** [comment]
I am again here!

Your Calendar app version `1.0` fails to build with the SDK version `0.100.1-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/65d25c86f6103d1702fefdcc/page)

Flipper Team

**Comment by techartdev** [comment]
App is updated
